name: Run ETL Pipeline

on:
  schedule:
    - cron: "0 2 * * *"  # every day at 2am UTC
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL script
        run: python src/ingest.py